server:
  port: 8081

spring:
  application:
    name: identity-service

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: hvs.MghJeeekEuv1CBLbvMpzR8S1

      kv:
        enabled: true
        backend: secret
        application-name: princemart

  datasource:
    url: jdbc:mysql://localhost:3306/pm_identity_db?createDatabaseIfNotExist=true
    username: root
    password: Sprince1*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.vault: DEBUG
