server:
  port: ${PORT:9000}

spring:
  application:
    name: SUBSCRIPTION-SERVICE

  datasource:
    url: ${SUB_DB_URL:jdbc:mysql://localhost:3306/pm_sub_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Sprince1*}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: princemart.princeinc@gmail.com
    password: lbxzbvbngbpacaas
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone: https://pm-server-registry.onrender.com/eureka/
