server:
  port: ${PORT:8091}

spring:
  application:
    name: coupon-service
  datasource:
    url: ${COUPON_DB_URL:jdbc:mysql://localhost:5432/pm_coupon_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Sprince1*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: https://pm-server-registry.onrender.com/eureka/
