server:
  port: ${PORT:8089}

spring:
  application:
    name: review-service
  datasource:
    url: ${REVIEW_DB_URL:jdbc:mysql://localhost:3306/pm_review_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Sprince1*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone: https://pm-server-registry.onrender.com/eureka/
