server:
  port: ${PORT:8086}

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/pm_payment_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Sprince1*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: true # Explicitly tell it to register
    fetch-registry: true # Explicitly tell it to fetch other services
    service-url:
      defaultZone: https://pm-server-registry.onrender.com/eureka/

razorpay:
  key:
    id: rzp_test_SWXiqwcwXnFIvp
    secret: JxvZ3SPu0lnRA9W9WgiEW4ET
